name: MSD Build and Test in hw3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Change to hw3 directory
      run: cd hw3

    - name: Build project
      run: |
        cd hw3
        make all

    - name: Run tests
      run: |
        cd hw3
        make test
