name: MSD
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change to Makefile directory
      working-directory: ./path/to/your/makefile
    - name: Run make test
      run: make test

